CREATE TABLE Users (
	[Id] UNIQUEIDENTIFIER CONSTRAINT PK_Users_Id PRIMARY KEY CONSTRAINT DF_User_Id DEFAULT NEWID(),
	[Email] NVARCHAR(50) NOT NULL CONSTRAINT UC_Email UNIQUE,
	[Password] NVARCHAR(50) NOT NULL,
	[Role] TINYINT NOT NULL
)