Create Table EventsUsers (
	[EventId] UNIQUEIDENTIFIER NOT NULL CONSTRAINT FK_EventsUsers_EventId FOREIGN KEY REFERENCES Events([Id]),
	[UserId] UNIQUEIDENTIFIER NOT NULL CONSTRAINT FK_EventsUsers_UserId FOREIGN KEY REFERENCES Users([Id])
)